# -*- coding: utf-8 -*-
"""AnaliseCandidatos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y7I1ydp1PtNhG6gE57iouclH6UkrdlgK
"""

import pandas as pd
import matplotlib.pyplot as plt

candidatos = pd.read_csv("candidatura_resumo_sem_duplicados.csv", sep= ',', encoding= 'latin1', low_memory=False)

# Método .split(',') transforma cada string em uma lista de strings, separando onde houver vírgula e cria uma nova coluna.
candidatos['ANOS_ELEICAO_LISTA'] = candidatos['ANO'].str.split(',')

#.len() em cada lista para contar quantos elementos tem nela (quantos anos) e guarda em uma nova coluna.
candidatos['NUM_ELEICOES'] = candidatos['ANOS_ELEICAO_LISTA'].str.len()

# Agrupa todas as linhas do DataFrame por nome do candidato e retrona o maior valor de NUM_ELEICOES para cada candidato, para evitar repetições.
eleicoes_por_candidato = candidatos.groupby('NM_CANDIDATO')['NUM_ELEICOES'].max()

# eleicoes_por_candidato conta com o índice sendo o nome do candidato e o valor o número de eleições. .value_counts()conta quantas vezes cada número de eleições aparece e ordena.
participacao_count = eleicoes_por_candidato.value_counts().sort_index()

plt.figure(figsize=(10, 6))
plt.bar(participacao_count.index, participacao_count.values)
plt.xlabel('Número de eleições')
plt.ylabel('Número de candidatos')
plt.title('Número de eleições por candidato')
plt.xlim(0, 16)
plt.xticks(ticks=range(0, 17, 1), rotation=45, ha='right')
plt.tight_layout()
plt.show()

# Filtra os candidatos que foram eleitos, considerando a SITUACAO_ELEICAO
candidatos_eleitos = candidatos[candidatos['SITUACAO_ELEICAO'].str.contains('ELEITO', na=False)]

eleicoes_por_candidato_eleito = candidatos_eleitos.groupby('NM_CANDIDATO')['NUM_ELEICOES'].max()

participacao_eleito_count = eleicoes_por_candidato_eleito.value_counts().sort_index()

plt.figure(figsize=(10, 6))
plt.bar(participacao_eleito_count.index, participacao_eleito_count.values)
plt.xlabel('Número de eleições')
plt.ylabel('Número de candidatos')
plt.title('Número de eleições por candidato (em algum momento eleito)')
plt.xlim(0, 16)
plt.xticks(ticks=range(0, 17, 1), rotation=45, ha='right')
plt.tight_layout()
plt.show()