# -*- coding: utf-8 -*-
"""Cópia de Candidatos/PopulaçãoTotal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12BKOCFNASd2Fvoc0nW7ftgEXfcbcUb0n
"""

import geopandas as gpd
import pandas as pd
import folium
from folium import Choropleth
import ipywidgets as widgets
from ipywidgets import interactive
from IPython.display import display, clear_output

br_estados = gpd.read_file("BR_UF_2024.shp")

br_geral = pd.read_csv("geralBrasil.csv", sep= ';', encoding= 'UTF-8', engine='python', on_bad_lines='warn')
br_candidatos04 = pd.read_csv("consulta_cand_2004_BRASIL.csv", sep= ';', encoding= 'latin1', engine='python', on_bad_lines='warn')
br_candidatos08 = pd.read_csv("consulta_cand_2008_BRASIL.csv", sep= ';', encoding= 'latin1', engine='python', on_bad_lines='warn')
br_candidatos12 = pd.read_csv("consulta_cand_2012_BRASIL.csv", sep= ';', encoding= 'latin1', engine='python', on_bad_lines='warn')
br_candidatos16 = pd.read_csv("consulta_cand_2016_BRASIL.csv", sep= ';', encoding= 'latin1', engine='python', on_bad_lines='warn')
br_candidatos20 = pd.read_csv("consulta_cand_2020_BRASIL.csv", sep= ';', encoding= 'latin1', engine='python', on_bad_lines='warn')
br_candidatos24 = pd.read_csv("consulta_cand_2024_BRASIL.csv", sep= ';', encoding= 'latin1', engine='python', on_bad_lines='warn')

contagem_estados04 = br_candidatos04['SG_UF'].value_counts()

dic_indice04 = {
    "AC" : contagem_estados04["AC"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "AC")]["2004"].values[0],
    "AL" : contagem_estados04["AL"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "AL")]["2004"].values[0],
    "AP" : contagem_estados04["AP"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "AP")]["2004"].values[0],
    "AM" : contagem_estados04["AM"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "AM")]["2004"].values[0],
    "BA" : contagem_estados04["BA"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "BA")]["2004"].values[0],
    "CE" : contagem_estados04["CE"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "CE")]["2004"].values[0],
   # "DF" : contagem_estados04["DF"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "DF")]["2004"].values[0],
    "ES" : contagem_estados04["ES"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "ES")]["2004"].values[0],
    "GO" : contagem_estados04["GO"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "GO")]["2004"].values[0],
    "MA" : contagem_estados04["MA"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "MA")]["2004"].values[0],
    "MT" : contagem_estados04["MT"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "MT")]["2004"].values[0],
    "MS" : contagem_estados04["MS"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "MS")]["2004"].values[0],
    "MG" : contagem_estados04["MG"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "MG")]["2004"].values[0],
    "PA" : contagem_estados04["PA"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PA")]["2004"].values[0],
    "PB" : contagem_estados04["PB"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PB")]["2004"].values[0],
    "PR" : contagem_estados04["PR"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PR")]["2004"].values[0],
    "PE" : contagem_estados04["PE"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PE")]["2004"].values[0],
    "PI" : contagem_estados04["PI"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PI")]["2004"].values[0],
    "RJ" : contagem_estados04["RJ"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RJ")]["2004"].values[0],
    "RN" : contagem_estados04["RN"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RN")]["2004"].values[0],
    "RO" : contagem_estados04["RO"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RO")]["2004"].values[0],
    "RR" : contagem_estados04["RR"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RR")]["2004"].values[0],
    "RS" : contagem_estados04["RS"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RS")]["2004"].values[0],
    "SC" : contagem_estados04["SC"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "SC")]["2004"].values[0],
    "SP" : contagem_estados04["SP"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "SP")]["2004"].values[0],
    "SE" : contagem_estados04["SE"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "SE")]["2004"].values[0],
    "TO"  : contagem_estados04["TO"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "TO")]["2004"].values[0]
}

dic_indice04 = {k: float(v) for k, v in dic_indice04.items()}

contagem_estados08 = br_candidatos08['SG_UF'].value_counts()

dic_indice08 = {
    "AC" : contagem_estados08["AC"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "AC")]["2008"].values[0],
    "AL" : contagem_estados08["AL"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "AL")]["2008"].values[0],
    "AP" : contagem_estados08["AP"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "AP")]["2008"].values[0],
    "AM" : contagem_estados08["AM"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "AM")]["2008"].values[0],
    "BA" : contagem_estados08["BA"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "BA")]["2008"].values[0],
    "CE" : contagem_estados08["CE"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "CE")]["2008"].values[0],
   # "DF" : contagem_estados08["DF"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "DF")]["2008"].values[0],
    "ES" : contagem_estados08["ES"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "ES")]["2008"].values[0],
    "GO" : contagem_estados08["GO"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "GO")]["2008"].values[0],
    "MA" : contagem_estados08["MA"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "MA")]["2008"].values[0],
    "MT" : contagem_estados08["MT"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "MT")]["2008"].values[0],
    "MS" : contagem_estados08["MS"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "MS")]["2008"].values[0],
    "MG" : contagem_estados08["MG"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "MG")]["2008"].values[0],
    "PA" : contagem_estados08["PA"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PA")]["2008"].values[0],
    "PB" : contagem_estados08["PB"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PB")]["2008"].values[0],
    "PR" : contagem_estados08["PR"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PR")]["2008"].values[0],
    "PE" : contagem_estados08["PE"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PE")]["2008"].values[0],
    "PI" : contagem_estados08["PI"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PI")]["2008"].values[0],
    "RJ" : contagem_estados08["RJ"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RJ")]["2008"].values[0],
    "RN" : contagem_estados08["RN"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RN")]["2008"].values[0],
    "RO" : contagem_estados08["RO"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RO")]["2008"].values[0],
    "RR" : contagem_estados08["RR"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RR")]["2008"].values[0],
    "RS" : contagem_estados08["RS"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RS")]["2008"].values[0],
    "SC" : contagem_estados08["SC"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "SC")]["2008"].values[0],
    "SP" : contagem_estados08["SP"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "SP")]["2008"].values[0],
    "SE" : contagem_estados08["SE"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "SE")]["2008"].values[0],
    "TO"  : contagem_estados08["TO"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "TO")]["2008"].values[0]
}

dic_indice08 = {k: float(v) for k, v in dic_indice08.items()}

contagem_estados12 = br_candidatos12['SG_UF'].value_counts()

dic_indice12 = {
    "AC" : contagem_estados12["AC"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "AC")]["2012"].values[0],
    "AL" : contagem_estados12["AL"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "AL")]["2012"].values[0],
    "AP" : contagem_estados12["AP"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "AP")]["2012"].values[0],
    "AM" : contagem_estados12["AM"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "AM")]["2012"].values[0],
    "BA" : contagem_estados12["BA"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "BA")]["2012"].values[0],
    "CE" : contagem_estados12["CE"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "CE")]["2012"].values[0],
   # "DF" : contagem_estados12["DF"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "DF")]["2012"].values[0],
    "ES" : contagem_estados12["ES"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "ES")]["2012"].values[0],
    "GO" : contagem_estados12["GO"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "GO")]["2012"].values[0],
    "MA" : contagem_estados12["MA"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "MA")]["2012"].values[0],
    "MT" : contagem_estados12["MT"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "MT")]["2012"].values[0],
    "MS" : contagem_estados12["MS"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "MS")]["2012"].values[0],
    "MG" : contagem_estados12["MG"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "MG")]["2012"].values[0],
    "PA" : contagem_estados12["PA"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PA")]["2012"].values[0],
    "PB" : contagem_estados12["PB"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PB")]["2012"].values[0],
    "PR" : contagem_estados12["PR"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PR")]["2012"].values[0],
    "PE" : contagem_estados12["PE"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PE")]["2012"].values[0],
    "PI" : contagem_estados12["PI"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PI")]["2012"].values[0],
    "RJ" : contagem_estados12["RJ"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RJ")]["2012"].values[0],
    "RN" : contagem_estados12["RN"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RN")]["2012"].values[0],
    "RO" : contagem_estados12["RO"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RO")]["2012"].values[0],
    "RR" : contagem_estados12["RR"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RR")]["2012"].values[0],
    "RS" : contagem_estados12["RS"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RS")]["2012"].values[0],
    "SC" : contagem_estados12["SC"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "SC")]["2012"].values[0],
    "SP" : contagem_estados12["SP"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "SP")]["2012"].values[0],
    "SE" : contagem_estados12["SE"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "SE")]["2012"].values[0],
    "TO"  : contagem_estados12["TO"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "TO")]["2012"].values[0]
}

dic_indice12 = {k: float(v) for k, v in dic_indice12.items()}

contagem_estados16 = br_candidatos16['SG_UF'].value_counts()

dic_indice16 = {
    "AC" : contagem_estados16["AC"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "AC")]["2016"].values[0],
    "AL" : contagem_estados16["AL"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "AL")]["2016"].values[0],
    "AP" : contagem_estados16["AP"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "AP")]["2016"].values[0],
    "AM" : contagem_estados16["AM"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "AM")]["2016"].values[0],
    "BA" : contagem_estados16["BA"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "BA")]["2016"].values[0],
    "CE" : contagem_estados16["CE"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "CE")]["2016"].values[0],
    #"DF" : contagem_estados16["DF"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "DF")]["2016"].values[0],
    "ES" : contagem_estados16["ES"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "ES")]["2016"].values[0],
    "GO" : contagem_estados16["GO"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "GO")]["2016"].values[0],
    "MA" : contagem_estados16["MA"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "MA")]["2016"].values[0],
    "MT" : contagem_estados16["MT"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "MT")]["2016"].values[0],
    "MS" : contagem_estados16["MS"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "MS")]["2016"].values[0],
    "MG" : contagem_estados16["MG"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "MG")]["2016"].values[0],
    "PA" : contagem_estados16["PA"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PA")]["2016"].values[0],
    "PB" : contagem_estados16["PB"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PB")]["2016"].values[0],
    "PR" : contagem_estados16["PR"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PR")]["2016"].values[0],
    "PE" : contagem_estados16["PE"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PE")]["2016"].values[0],
    "PI" : contagem_estados16["PI"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PI")]["2016"].values[0],
    "RJ" : contagem_estados16["RJ"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RJ")]["2016"].values[0],
    "RN" : contagem_estados16["RN"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RN")]["2016"].values[0],
    "RO" : contagem_estados16["RO"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RO")]["2016"].values[0],
    "RR" : contagem_estados16["RR"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RR")]["2016"].values[0],
    "RS" : contagem_estados16["RS"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RS")]["2016"].values[0],
    "SC" : contagem_estados16["SC"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "SC")]["2016"].values[0],
    "SP" : contagem_estados16["SP"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "SP")]["2016"].values[0],
    "SE" : contagem_estados16["SE"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "SE")]["2016"].values[0],
    "TO"  : contagem_estados16["TO"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "TO")]["2016"].values[0]
}

dic_indice16 = {k: float(v) for k, v in dic_indice16.items()}

contagem_estados20 = br_candidatos20['SG_UF'].value_counts()

dic_indice20 = {
    "AC" : contagem_estados20["AC"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "AC")]["2020"].values[0],
    "AL" : contagem_estados20["AL"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "AL")]["2020"].values[0],
    "AP" : contagem_estados20["AP"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "AP")]["2020"].values[0],
    "AM" : contagem_estados20["AM"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "AM")]["2020"].values[0],
    "BA" : contagem_estados20["BA"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "BA")]["2020"].values[0],
    "CE" : contagem_estados20["CE"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "CE")]["2020"].values[0],
    #"DF" : contagem_estados20["DF"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "DF")]["2020"].values[0],
    "ES" : contagem_estados20["ES"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "ES")]["2020"].values[0],
    "GO" : contagem_estados20["GO"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "GO")]["2020"].values[0],
    "MA" : contagem_estados20["MA"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "MA")]["2020"].values[0],
    "MT" : contagem_estados20["MT"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "MT")]["2020"].values[0],
    "MS" : contagem_estados20["MS"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "MS")]["2020"].values[0],
    "MG" : contagem_estados20["MG"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "MG")]["2020"].values[0],
    "PA" : contagem_estados20["PA"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PA")]["2020"].values[0],
    "PB" : contagem_estados20["PB"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PB")]["2020"].values[0],
    "PR" : contagem_estados20["PR"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PR")]["2020"].values[0],
    "PE" : contagem_estados20["PE"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PE")]["2020"].values[0],
    "PI" : contagem_estados20["PI"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PI")]["2020"].values[0],
    "RJ" : contagem_estados20["RJ"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RJ")]["2020"].values[0],
    "RN" : contagem_estados20["RN"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RN")]["2020"].values[0],
    "RO" : contagem_estados20["RO"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RO")]["2020"].values[0],
    "RR" : contagem_estados20["RR"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RR")]["2020"].values[0],
    "RS" : contagem_estados20["RS"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RS")]["2020"].values[0],
    "SC" : contagem_estados20["SC"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "SC")]["2020"].values[0],
    "SP" : contagem_estados20["SP"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "SP")]["2020"].values[0],
    "SE" : contagem_estados20["SE"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "SE")]["2020"].values[0],
    "TO"  : contagem_estados20["TO"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "TO")]["2020"].values[0]
}

dic_indice20 = {k: float(v) for k, v in dic_indice20.items()}

contagem_estados24 = br_candidatos24['SG_UF'].value_counts()

dic_indice24 = {
    "AC" : contagem_estados24["AC"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "AC")]["2024"].values[0],
    "AL" : contagem_estados24["AL"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "AL")]["2024"].values[0],
    "AP" : contagem_estados24["AP"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "AP")]["2024"].values[0],
    "AM" : contagem_estados24["AM"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "AM")]["2024"].values[0],
    "BA" : contagem_estados24["BA"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "BA")]["2024"].values[0],
    "CE" : contagem_estados24["CE"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "CE")]["2024"].values[0],
   # "DF" : contagem_estados24["DF"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "DF")]["2024"].values[0],
    "ES" : contagem_estados24["ES"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "ES")]["2024"].values[0],
    "GO" : contagem_estados24["GO"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "GO")]["2024"].values[0],
    "MA" : contagem_estados24["MA"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "MA")]["2024"].values[0],
    "MT" : contagem_estados24["MT"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "MT")]["2024"].values[0],
    "MS" : contagem_estados24["MS"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "MS")]["2024"].values[0],
    "MG" : contagem_estados24["MG"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "MG")]["2024"].values[0],
    "PA" : contagem_estados24["PA"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PA")]["2024"].values[0],
    "PB" : contagem_estados24["PB"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PB")]["2024"].values[0],
    "PR" : contagem_estados24["PR"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PR")]["2024"].values[0],
    "PE" : contagem_estados24["PE"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PE")]["2024"].values[0],
    "PI" : contagem_estados24["PI"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "PI")]["2024"].values[0],
    "RJ" : contagem_estados24["RJ"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RJ")]["2024"].values[0],
    "RN" : contagem_estados24["RN"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RN")]["2024"].values[0],
    "RO" : contagem_estados24["RO"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RO")]["2024"].values[0],
    "RR" : contagem_estados24["RR"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RR")]["2024"].values[0],
    "RS" : contagem_estados24["RS"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "RS")]["2024"].values[0],
    "SC" : contagem_estados24["SC"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "SC")]["2024"].values[0],
    "SP" : contagem_estados24["SP"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "SP")]["2024"].values[0],
    "SE" : contagem_estados24["SE"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "SE")]["2024"].values[0],
    "TO"  : contagem_estados24["TO"]/br_geral[(br_geral["Brasil e Unidade da Federação"] == "TO")]["2024"].values[0]
}

dic_indice24 = {k: float(v) for k, v in dic_indice24.items()}

slider_ano = widgets.IntSlider(value=2004, min=2004, max=2024, step=4, description="Ano:")

output = widgets.Output()

def busca_func(change):
    with output:
        clear_output()
        ano = str(slider_ano.value)

        if ano == "2004":
          mapaCandidatoPopulacao04 = folium.Map(location=[-15.788497, -47.879873], zoom_start=4)
          folium.Choropleth(
              geo_data=br_estados,
              name="choropleth",
              data=dic_indice04,
              key_on="feature.properties.SIGLA_UF",
              fill_color="Reds",
              fill_opacity=0.7,
              line_opacity=0.2,
              legend_name="Relação população total/candidatos políticos em 2004",
          ).add_to(mapaCandidatoPopulacao04)
          display(mapaCandidatoPopulacao04)
        elif ano == "2008":
          mapaCandidatoPopulacao08 = folium.Map(location=[-15.788497, -47.879873], zoom_start=4)
          folium.Choropleth(
              geo_data=br_estados,
              name="choropleth",
              data=dic_indice08,
              key_on="feature.properties.SIGLA_UF",
              fill_color="Reds",
              fill_opacity=0.7,
              line_opacity=0.2,
              legend_name="Relação população total/candidatos políticos em 2008",
          ).add_to(mapaCandidatoPopulacao08)
          display(mapaCandidatoPopulacao08)
        elif ano == "2012":
          mapaCandidatoPopulacao12 = folium.Map(location=[-15.788497, -47.879873], zoom_start=4)
          folium.Choropleth(
              geo_data=br_estados,
              name="choropleth",
              data=dic_indice12,
              key_on="feature.properties.SIGLA_UF",
              fill_color="Reds",
              fill_opacity=0.7,
              line_opacity=0.2,
              legend_name="Relação população total/candidatos políticos em 2012",
          ).add_to(mapaCandidatoPopulacao12)
          display(mapaCandidatoPopulacao12)
        elif ano == "2016":
          mapaCandidatoPopulacao16 = folium.Map(location=[-15.788497, -47.879873], zoom_start=4)
          folium.Choropleth(
              geo_data=br_estados,
              name="choropleth",
              data=dic_indice16,
              key_on="feature.properties.SIGLA_UF",
              fill_color="Reds",
              fill_opacity=0.7,
              line_opacity=0.2,
              legend_name="Relação população total/candidatos políticos em 2016",
          ).add_to(mapaCandidatoPopulacao16)
          display(mapaCandidatoPopulacao16)
        elif ano == "2020":
          mapaCandidatoPopulacao20 = folium.Map(location=[-15.788497, -47.879873], zoom_start=4)
          folium.Choropleth(
              geo_data=br_estados,
              name="choropleth",
              data=dic_indice20,
              key_on="feature.properties.SIGLA_UF",
              fill_color="Reds",
              fill_opacity=0.7,
              line_opacity=0.2,
              legend_name="Relação população total/candidatos políticos em 2020",
          ).add_to(mapaCandidatoPopulacao20)
          display(mapaCandidatoPopulacao20)
        elif ano == "2024":
          mapaCandidatoPopulacao24 = folium.Map(location=[-15.788497, -47.879873], zoom_start=4)
          folium.Choropleth(
              geo_data=br_estados,
              name="choropleth",
              data=dic_indice24,
              key_on="feature.properties.SIGLA_UF",
              fill_color="Reds",
              fill_opacity=0.7,
              line_opacity=0.2,
              legend_name="Relação população total/candidatos políticos em 2024",
          ).add_to(mapaCandidatoPopulacao24)
          display(mapaCandidatoPopulacao24)

slider_ano.observe(busca_func, names='value')

display(slider_ano)
display(output)

busca_func(None)