# -*- coding: utf-8 -*-
"""FaixaEtariaCandidaturas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rY58kZlbCYO5azb91uCvjxefynM2FNTF
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

faixaetaria = pd.read_csv('faixaetaria.csv', sep= ';', encoding= 'latin1')

faixaetaria

faixaetaria['Porcentagem'] = faixaetaria['Porcentagem'].str.replace(',','.')
faixaetaria["Porcentagem"] = pd.to_numeric(faixaetaria["Porcentagem"], errors='coerce')
faixaetaria["Porcentagem"] = faixaetaria["Porcentagem"] * 100

faixaetaria = faixaetaria[faixaetaria['Faixa etária'] != 'Não divulgável']
faixaetaria = faixaetaria[faixaetaria['Faixa etária'] != 'Inválida']
faixaetaria = faixaetaria[faixaetaria['Faixa etária'] != '16 anos']
faixaetaria = faixaetaria[faixaetaria['Faixa etária'] != '17 anos']
faixaetaria = faixaetaria[faixaetaria['Faixa etária'] != '18 anos']
faixaetaria = faixaetaria[faixaetaria['Faixa etária'] != '19 anos']
faixaetaria = faixaetaria[faixaetaria['Faixa etária'] != '20 anos']
faixaetaria = faixaetaria[faixaetaria['Faixa etária'] != '75 a 79 anos']
faixaetaria = faixaetaria[faixaetaria['Faixa etária'] != '80 a 84 anos']
faixaetaria = faixaetaria[faixaetaria['Faixa etária'] != '85 a 89 anos']
faixaetaria = faixaetaria[faixaetaria['Faixa etária'] != '90 a 94 anos']
faixaetaria = faixaetaria[faixaetaria['Faixa etária'] != '95 a 99 anos']
faixaetaria = faixaetaria[faixaetaria['Faixa etária'] != '100 anos ou mais']

sns.lineplot(data=faixaetaria,x='Ano',y='Porcentagem',hue='Faixa etária', style='Faixa etária', markers=True).set(title='Faixa etária da candidatura 1996 a 2024', xlabel='Ano', ylabel='Porcentagem')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.xticks(range(1996, 2025, 4))

faixaetaria_ajustada = faixaetaria[faixaetaria['Ano'] != 1996]
faixaetaria_ajustada

sns.lineplot(data=faixaetaria_ajustada,x='Ano',y='Quantitativo',hue='Faixa etária', style='Faixa etária', markers=True).set(title='Faixa etária da candidatura 2000 a 2024', xlabel='Ano', ylabel='Quantitativo')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.xticks(range(2000, 2025, 4))

deputadoe_faixaetaria = pd.read_csv('deputadoe_faixaetaria.csv', sep= ';', encoding= 'latin1' )
deputadof_faixaetaria = pd.read_csv('deputadof_faixaetaria.csv', sep= ';', encoding= 'latin1' )
vereador_faixaetaria = pd.read_csv('vereador_faixaetaria.csv', sep= ';', encoding= 'latin1' )
prefeito_faixaetaria = pd.read_csv('prefeito_faixaetaria.csv', sep= ';', encoding= 'latin1' )

deputadoe_faixaetaria['Porcentagem'] = deputadoe_faixaetaria['Porcentagem'].str.replace(',','.')
deputadoe_faixaetaria["Porcentagem"] = pd.to_numeric(deputadoe_faixaetaria["Porcentagem"], errors='coerce')
deputadof_faixaetaria['Porcentagem'] = deputadof_faixaetaria['Porcentagem'].str.replace(',','.')
deputadof_faixaetaria["Porcentagem"] = pd.to_numeric(deputadof_faixaetaria["Porcentagem"], errors='coerce')
vereador_faixaetaria['Porcentagem'] = vereador_faixaetaria['Porcentagem'].str.replace(',','.')
vereador_faixaetaria["Porcentagem"] = pd.to_numeric(vereador_faixaetaria["Porcentagem"], errors='coerce')
prefeito_faixaetaria['Porcentagem'] = prefeito_faixaetaria['Porcentagem'].str.replace(',','.')
prefeito_faixaetaria["Porcentagem"] = pd.to_numeric(prefeito_faixaetaria["Porcentagem"], errors='coerce')

sns.lineplot(data=deputadoe_faixaetaria,x='Ano',y='Porcentagem',hue='Faixa etária', style='Faixa etária', markers=True).set(title='Faixa etária da candidatura de deputados estaduais entre 1998 e 2022', xlabel='Ano', ylabel='Porcentagem')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.xticks(range(1998, 2023, 4))

sns.lineplot(data=deputadoe_faixaetaria,x='Ano',y='Quantitativo',hue='Faixa etária', style='Faixa etária', markers=True).set(title='Faixa etária da candidatura de deputados estaduais entre 1998 e 2022', xlabel='Ano', ylabel='Quantitativo')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.xticks(range(1998, 2023, 4))

sns.lineplot(data=deputadof_faixaetaria,x='Ano',y='Porcentagem',hue='Faixa etária', style='Faixa etária', markers=True).set(title='Faixa etária da candidatura de deputados federais entre 1998 e 2022', xlabel='Ano', ylabel='Porcentagem')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.xticks(range(1998, 2023, 4))

sns.lineplot(data=deputadof_faixaetaria,x='Ano',y='Quantitativo',hue='Faixa etária', style='Faixa etária', markers=True).set(title='Faixa etária da candidatura de deputados federais entre 1998 e 2022', xlabel='Ano', ylabel='Quantitativo')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.xticks(range(1998, 2023, 4))

sns.lineplot(data=vereador_faixaetaria,x='Ano',y='Porcentagem',hue='Faixa etária', style='Faixa etária', markers=True).set(title='Faixa etária da candidatura de vereadores entre 2000 e 2024', xlabel='Ano', ylabel='Porcentagem')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=vereador_faixaetaria,x='Ano',y='Quantitativo',hue='Faixa etária', style='Faixa etária', markers=True).set(title='Faixa etária da candidatura de vereadores entre 2000 e 2024', xlabel='Ano', ylabel='Quantitativo')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=prefeito_faixaetaria,x='Ano',y='Porcentagem',hue='Faixa etária', style='Faixa etária', markers=True).set(title='Faixa etária da candidatura de prefeitos entre 2000 e 2024', xlabel='Ano', ylabel='Porcentagem')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=prefeito_faixaetaria,x='Ano',y='Quantitativo',hue='Faixa etária', style='Faixa etária', markers=True).set(title='Faixa etária da candidatura de prefeitos entre 2000 e 2024', xlabel='Ano', ylabel='Quantitativo')
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.xticks(range(2000, 2025, 4))