# -*- coding: utf-8 -*-
"""Cópia de Cópia de geopandasColigacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AFRlPNEdV0apF0agqSHI-UOQxKvP9T4b
"""

import geopandas as gpd
import pandas as pd
import folium
from folium import Choropleth
import ipywidgets as widgets
from ipywidgets import interactive
from IPython.display import display, clear_output, IFrame

br_estados = gpd.read_file("BR_UF_2024.shp")

regiaoc00 = pd.read_csv("consulta_coligacao_2000.csv", sep= ';', encoding= 'latin1')
regiaoc04 = pd.read_csv("consulta_coligacao_2004.csv", sep= ';', encoding= 'latin1')
regiaoc08 = pd.read_csv("consulta_coligacao_2008.csv", sep= ';', encoding= 'latin1')
regiaoc12 = pd.read_csv("consulta_coligacao_2012.csv", sep= ';', encoding= 'latin1')
regiaoc16 = pd.read_csv("consulta_coligacao_2016.csv", sep= ';', encoding= 'latin1')
regiaoc20 = pd.read_csv("consulta_coligacao_2020.csv", sep= ';', encoding= 'latin1')
regiaoc24 = pd.read_csv("consulta_coligacao_2024.csv", sep= ';', encoding= 'latin1')

dic_estados00 = {
    "AC" : len(regiaoc00[regiaoc00['SG_UF']=="AC"]),
    "AL" : len(regiaoc00[regiaoc00['SG_UF']=="AL"]),
    "AP" : len(regiaoc00[regiaoc00['SG_UF']=="AP"]),
    "AM" : len(regiaoc00[regiaoc00['SG_UF']=="AM"]),
    "BA" : len(regiaoc00[regiaoc00['SG_UF']=="BA"]),
    "CE" : len(regiaoc00[regiaoc00['SG_UF']=="CE"]),
    "ES" : len(regiaoc00[regiaoc00['SG_UF']=="ES"]),
    "GO" : len(regiaoc00[regiaoc00['SG_UF']=="GO"]),
    "MA" : len(regiaoc00[regiaoc00['SG_UF']=="MA"]),
    "MT" : len(regiaoc00[regiaoc00['SG_UF']=="MT"]),
    "MS" : len(regiaoc00[regiaoc00['SG_UF']=="MS"]),
    "MG" : len(regiaoc00[regiaoc00['SG_UF']=="MG"]),
    "PA" : len(regiaoc00[regiaoc00['SG_UF']=="PA"]),
    "PB" : len(regiaoc00[regiaoc00['SG_UF']=="PB"]),
    "PR" : len(regiaoc00[regiaoc00['SG_UF']=="PR"]),
    "PE" : len(regiaoc00[regiaoc00['SG_UF']=="PE"]),
    "PI" : len(regiaoc00[regiaoc00['SG_UF']=="PI"]),
    "RJ" : len(regiaoc00[regiaoc00['SG_UF']=="RJ"]),
    "RN" : len(regiaoc00[regiaoc00['SG_UF']=="RN"]),
    "RO" : len(regiaoc00[regiaoc00['SG_UF']=="RO"]),
    "RR" : len(regiaoc00[regiaoc00['SG_UF']=="RR"]),
    "RS" : len(regiaoc00[regiaoc00['SG_UF']=="RS"]),
    "SC" : len(regiaoc00[regiaoc00['SG_UF']=="SC"]),
    "SP" : len(regiaoc00[regiaoc00['SG_UF']=="SP"]),
    "SE" : len(regiaoc00[regiaoc00['SG_UF']=="SE"]),
    "TO" : len(regiaoc00[regiaoc00['SG_UF']=="TO"])}

dic_estados04 = {
    "AC" : len(regiaoc04[regiaoc04['SG_UF']=="AC"]),
    "AL" : len(regiaoc04[regiaoc04['SG_UF']=="AL"]),
    "AP" : len(regiaoc04[regiaoc04['SG_UF']=="AP"]),
    "AM" : len(regiaoc04[regiaoc04['SG_UF']=="AM"]),
    "BA" : len(regiaoc04[regiaoc04['SG_UF']=="BA"]),
    "CE" : len(regiaoc04[regiaoc04['SG_UF']=="CE"]),
    "ES" : len(regiaoc04[regiaoc04['SG_UF']=="ES"]),
    "GO" : len(regiaoc04[regiaoc04['SG_UF']=="GO"]),
    "MA" : len(regiaoc04[regiaoc04['SG_UF']=="MA"]),
    "MT" : len(regiaoc04[regiaoc04['SG_UF']=="MT"]),
    "MS" : len(regiaoc04[regiaoc04['SG_UF']=="MS"]),
    "MG" : len(regiaoc04[regiaoc04['SG_UF']=="MG"]),
    "PA" : len(regiaoc04[regiaoc04['SG_UF']=="PA"]),
    "PB" : len(regiaoc04[regiaoc04['SG_UF']=="PB"]),
    "PR" : len(regiaoc04[regiaoc04['SG_UF']=="PR"]),
    "PE" : len(regiaoc04[regiaoc04['SG_UF']=="PE"]),
    "PI" : len(regiaoc04[regiaoc04['SG_UF']=="PI"]),
    "RJ" : len(regiaoc04[regiaoc04['SG_UF']=="RJ"]),
    "RN" : len(regiaoc04[regiaoc04['SG_UF']=="RN"]),
    "RO" : len(regiaoc04[regiaoc04['SG_UF']=="RO"]),
    "RR" : len(regiaoc04[regiaoc04['SG_UF']=="RR"]),
    "RS" : len(regiaoc04[regiaoc04['SG_UF']=="RS"]),
    "SC" : len(regiaoc04[regiaoc04['SG_UF']=="SC"]),
    "SP" : len(regiaoc04[regiaoc04['SG_UF']=="SP"]),
    "SE" : len(regiaoc04[regiaoc04['SG_UF']=="SE"]),
    "TO" : len(regiaoc04[regiaoc04['SG_UF']=="TO"])}

dic_estados08 = {
    "AC" : len(regiaoc08[regiaoc08['SG_UF']=="AC"]),
    "AL" : len(regiaoc08[regiaoc08['SG_UF']=="AL"]),
    "AP" : len(regiaoc08[regiaoc08['SG_UF']=="AP"]),
    "AM" : len(regiaoc08[regiaoc08['SG_UF']=="AM"]),
    "BA" : len(regiaoc08[regiaoc08['SG_UF']=="BA"]),
    "CE" : len(regiaoc08[regiaoc08['SG_UF']=="CE"]),
    "ES" : len(regiaoc08[regiaoc08['SG_UF']=="ES"]),
    "GO" : len(regiaoc08[regiaoc08['SG_UF']=="GO"]),
    "MA" : len(regiaoc08[regiaoc08['SG_UF']=="MA"]),
    "MT" : len(regiaoc08[regiaoc08['SG_UF']=="MT"]),
    "MS" : len(regiaoc08[regiaoc08['SG_UF']=="MS"]),
    "MG" : len(regiaoc08[regiaoc08['SG_UF']=="MG"]),
    "PA" : len(regiaoc08[regiaoc08['SG_UF']=="PA"]),
    "PB" : len(regiaoc08[regiaoc08['SG_UF']=="PB"]),
    "PR" : len(regiaoc08[regiaoc08['SG_UF']=="PR"]),
    "PE" : len(regiaoc08[regiaoc08['SG_UF']=="PE"]),
    "PI" : len(regiaoc08[regiaoc08['SG_UF']=="PI"]),
    "RJ" : len(regiaoc08[regiaoc08['SG_UF']=="RJ"]),
    "RN" : len(regiaoc08[regiaoc08['SG_UF']=="RN"]),
    "RO" : len(regiaoc08[regiaoc08['SG_UF']=="RO"]),
    "RR" : len(regiaoc08[regiaoc08['SG_UF']=="RR"]),
    "RS" : len(regiaoc08[regiaoc08['SG_UF']=="RS"]),
    "SC" : len(regiaoc08[regiaoc08['SG_UF']=="SC"]),
    "SP" : len(regiaoc08[regiaoc08['SG_UF']=="SP"]),
    "SE" : len(regiaoc08[regiaoc08['SG_UF']=="SE"]),
    "TO" : len(regiaoc08[regiaoc08['SG_UF']=="TO"])}

dic_estados12 = {
    "AC" : len(regiaoc12[regiaoc12['SG_UF']=="AC"]),
    "AL" : len(regiaoc12[regiaoc12['SG_UF']=="AL"]),
    "AP" : len(regiaoc12[regiaoc12['SG_UF']=="AP"]),
    "AM" : len(regiaoc12[regiaoc12['SG_UF']=="AM"]),
    "BA" : len(regiaoc12[regiaoc12['SG_UF']=="BA"]),
    "CE" : len(regiaoc12[regiaoc12['SG_UF']=="CE"]),
    "ES" : len(regiaoc12[regiaoc12['SG_UF']=="ES"]),
    "GO" : len(regiaoc12[regiaoc12['SG_UF']=="GO"]),
    "MA" : len(regiaoc12[regiaoc12['SG_UF']=="MA"]),
    "MT" : len(regiaoc12[regiaoc12['SG_UF']=="MT"]),
    "MS" : len(regiaoc12[regiaoc12['SG_UF']=="MS"]),
    "MG" : len(regiaoc12[regiaoc12['SG_UF']=="MG"]),
    "PA" : len(regiaoc12[regiaoc12['SG_UF']=="PA"]),
    "PB" : len(regiaoc12[regiaoc12['SG_UF']=="PB"]),
    "PR" : len(regiaoc12[regiaoc12['SG_UF']=="PR"]),
    "PE" : len(regiaoc12[regiaoc12['SG_UF']=="PE"]),
    "PI" : len(regiaoc12[regiaoc12['SG_UF']=="PI"]),
    "RJ" : len(regiaoc12[regiaoc12['SG_UF']=="RJ"]),
    "RN" : len(regiaoc12[regiaoc12['SG_UF']=="RN"]),
    "RO" : len(regiaoc12[regiaoc12['SG_UF']=="RO"]),
    "RR" : len(regiaoc12[regiaoc12['SG_UF']=="RR"]),
    "RS" : len(regiaoc12[regiaoc12['SG_UF']=="RS"]),
    "SC" : len(regiaoc12[regiaoc12['SG_UF']=="SC"]),
    "SP" : len(regiaoc12[regiaoc12['SG_UF']=="SP"]),
    "SE" : len(regiaoc12[regiaoc12['SG_UF']=="SE"]),
    "TO" : len(regiaoc12[regiaoc12['SG_UF']=="TO"])}

dic_estados16 = {
    "AC" : len(regiaoc16[regiaoc16['SG_UF']=="AC"]),
    "AL" : len(regiaoc16[regiaoc16['SG_UF']=="AL"]),
    "AP" : len(regiaoc16[regiaoc16['SG_UF']=="AP"]),
    "AM" : len(regiaoc16[regiaoc16['SG_UF']=="AM"]),
    "BA" : len(regiaoc16[regiaoc16['SG_UF']=="BA"]),
    "CE" : len(regiaoc16[regiaoc16['SG_UF']=="CE"]),
    "ES" : len(regiaoc16[regiaoc16['SG_UF']=="ES"]),
    "GO" : len(regiaoc16[regiaoc16['SG_UF']=="GO"]),
    "MA" : len(regiaoc16[regiaoc16['SG_UF']=="MA"]),
    "MT" : len(regiaoc16[regiaoc16['SG_UF']=="MT"]),
    "MS" : len(regiaoc16[regiaoc16['SG_UF']=="MS"]),
    "MG" : len(regiaoc16[regiaoc16['SG_UF']=="MG"]),
    "PA" : len(regiaoc16[regiaoc16['SG_UF']=="PA"]),
    "PB" : len(regiaoc16[regiaoc16['SG_UF']=="PB"]),
    "PR" : len(regiaoc16[regiaoc16['SG_UF']=="PR"]),
    "PE" : len(regiaoc16[regiaoc16['SG_UF']=="PE"]),
    "PI" : len(regiaoc16[regiaoc16['SG_UF']=="PI"]),
    "RJ" : len(regiaoc16[regiaoc16['SG_UF']=="RJ"]),
    "RN" : len(regiaoc16[regiaoc16['SG_UF']=="RN"]),
    "RO" : len(regiaoc16[regiaoc16['SG_UF']=="RO"]),
    "RR" : len(regiaoc16[regiaoc16['SG_UF']=="RR"]),
    "RS" : len(regiaoc16[regiaoc16['SG_UF']=="RS"]),
    "SC" : len(regiaoc16[regiaoc16['SG_UF']=="SC"]),
    "SP" : len(regiaoc16[regiaoc16['SG_UF']=="SP"]),
    "SE" : len(regiaoc16[regiaoc16['SG_UF']=="SE"]),
    "TO" : len(regiaoc16[regiaoc16['SG_UF']=="TO"])}

dic_estados20 = {
    "AC" : len(regiaoc20[regiaoc20['SG_UF']=="AC"]),
    "AL" : len(regiaoc20[regiaoc20['SG_UF']=="AL"]),
    "AP" : len(regiaoc20[regiaoc20['SG_UF']=="AP"]),
    "AM" : len(regiaoc20[regiaoc20['SG_UF']=="AM"]),
    "BA" : len(regiaoc20[regiaoc20['SG_UF']=="BA"]),
    "CE" : len(regiaoc20[regiaoc20['SG_UF']=="CE"]),
    "ES" : len(regiaoc20[regiaoc20['SG_UF']=="ES"]),
    "GO" : len(regiaoc20[regiaoc20['SG_UF']=="GO"]),
    "MA" : len(regiaoc20[regiaoc20['SG_UF']=="MA"]),
    "MT" : len(regiaoc20[regiaoc20['SG_UF']=="MT"]),
    "MS" : len(regiaoc20[regiaoc20['SG_UF']=="MS"]),
    "MG" : len(regiaoc20[regiaoc20['SG_UF']=="MG"]),
    "PA" : len(regiaoc20[regiaoc20['SG_UF']=="PA"]),
    "PB" : len(regiaoc20[regiaoc20['SG_UF']=="PB"]),
    "PR" : len(regiaoc20[regiaoc20['SG_UF']=="PR"]),
    "PE" : len(regiaoc20[regiaoc20['SG_UF']=="PE"]),
    "PI" : len(regiaoc20[regiaoc20['SG_UF']=="PI"]),
    "RJ" : len(regiaoc20[regiaoc20['SG_UF']=="RJ"]),
    "RN" : len(regiaoc20[regiaoc20['SG_UF']=="RN"]),
    "RO" : len(regiaoc20[regiaoc20['SG_UF']=="RO"]),
    "RR" : len(regiaoc20[regiaoc20['SG_UF']=="RR"]),
    "RS" : len(regiaoc20[regiaoc20['SG_UF']=="RS"]),
    "SC" : len(regiaoc20[regiaoc20['SG_UF']=="SC"]),
    "SP" : len(regiaoc20[regiaoc20['SG_UF']=="SP"]),
    "SE" : len(regiaoc20[regiaoc20['SG_UF']=="SE"]),
    "TO" : len(regiaoc20[regiaoc20['SG_UF']=="TO"])}

dic_estados24 = {
    "AC" : len(regiaoc04[regiaoc04['SG_UF']=="AC"]),
    "AL" : len(regiaoc04[regiaoc04['SG_UF']=="AL"]),
    "AP" : len(regiaoc04[regiaoc04['SG_UF']=="AP"]),
    "AM" : len(regiaoc04[regiaoc04['SG_UF']=="AM"]),
    "BA" : len(regiaoc04[regiaoc04['SG_UF']=="BA"]),
    "CE" : len(regiaoc04[regiaoc04['SG_UF']=="CE"]),
    "ES" : len(regiaoc04[regiaoc04['SG_UF']=="ES"]),
    "GO" : len(regiaoc04[regiaoc04['SG_UF']=="GO"]),
    "MA" : len(regiaoc04[regiaoc04['SG_UF']=="MA"]),
    "MT" : len(regiaoc04[regiaoc04['SG_UF']=="MT"]),
    "MS" : len(regiaoc04[regiaoc04['SG_UF']=="MS"]),
    "MG" : len(regiaoc04[regiaoc04['SG_UF']=="MG"]),
    "PA" : len(regiaoc04[regiaoc04['SG_UF']=="PA"]),
    "PB" : len(regiaoc04[regiaoc04['SG_UF']=="PB"]),
    "PR" : len(regiaoc04[regiaoc04['SG_UF']=="PR"]),
    "PE" : len(regiaoc04[regiaoc04['SG_UF']=="PE"]),
    "PI" : len(regiaoc04[regiaoc04['SG_UF']=="PI"]),
    "RJ" : len(regiaoc04[regiaoc04['SG_UF']=="RJ"]),
    "RN" : len(regiaoc04[regiaoc04['SG_UF']=="RN"]),
    "RO" : len(regiaoc04[regiaoc04['SG_UF']=="RO"]),
    "RR" : len(regiaoc04[regiaoc04['SG_UF']=="RR"]),
    "RS" : len(regiaoc04[regiaoc04['SG_UF']=="RS"]),
    "SC" : len(regiaoc04[regiaoc04['SG_UF']=="SC"]),
    "SP" : len(regiaoc04[regiaoc04['SG_UF']=="SP"]),
    "SE" : len(regiaoc04[regiaoc04['SG_UF']=="SE"]),
    "TO" : len(regiaoc04[regiaoc04['SG_UF']=="TO"])}

dados = {
    "2000": dic_estados00,
    "2004": dic_estados04,
    "2008": dic_estados08,
    "2012": dic_estados12,
    "2016": dic_estados16,
    "2020": dic_estados20,
    "2024": dic_estados24,
}

slider_ano = widgets.IntSlider(value=2000, min=2000, max=2024, step=4, description="Ano:")

output = widgets.Output()

def busca_func(change):
    with output:
        clear_output()
        ano = str(slider_ano.value)
        mapaColigacao = folium.Map(location=[-15.788497, -47.879873], zoom_start=4)
        folium.Choropleth(
              geo_data=br_estados,
              name="choropleth",
              data=dados[ano],
              key_on="feature.properties.SIGLA_UF",
              fill_color="Oranges",
              fill_opacity=0.7,
              line_opacity=0.2,
              legend_name=f"Número de coligações em cada estado em {ano}",
        ).add_to(mapaColigacao)
        display(mapaColigacao)


slider_ano.observe(busca_func, names='value')

display(slider_ano)
display(output)

busca_func(None)