# -*- coding: utf-8 -*-
"""Coligação.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vrFTs00xqe5vO8OAdgi6h28z08Lf5tVT
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import unicodedata

coligacao24 = pd.read_csv('consulta_coligacao_2024.csv', sep = ';', encoding='latin-1')
coligacao20 = pd.read_csv('consulta_coligacao_2020.csv', sep = ';', encoding='latin-1')
coligacao16 = pd.read_csv('consulta_coligacao_2016.csv', sep = ';', encoding='latin-1')
coligacao12 = pd.read_csv('consulta_coligacao_2012.csv', sep = ';', encoding='latin-1')
coligacao08 = pd.read_csv('consulta_coligacao_2008.csv', sep = ';', encoding='latin-1')
coligacao04 = pd.read_csv('consulta_coligacao_2004.csv', sep = ';', encoding='latin-1')
coligacao00 = pd.read_csv('consulta_coligacao_2000.csv', sep = ';', encoding='latin-1')

coligacao = pd.concat([coligacao24, coligacao20, coligacao16, coligacao12, coligacao08, coligacao04, coligacao00])

estados = ['AC', 'AL', 'AM', 'AP', 'BA', 'CE', 'ES', 'GO', 'MA', 'MS', 'MT', 'PA', 'PB', 'PE', 'PI', 'PR', 'RJ', 'RN', 'RO', 'RR', 'RS', 'SC', 'SE', 'SP', 'TO']

def media_estado(ano, soma, total, dic1, dic2, dic3):
  for x in estados:
    for index, row in coligacao.iterrows():
      if row['SG_UF'] == x and row['ANO_ELEICAO'] == ano:
        total = total + 1
        soma = soma + 1
        dic1[x] = total
        dic2[x] = soma
        for y in str(row['DS_COMPOSICAO_COLIGACAO']):
          if y == '/':
            soma = soma + 1
            dic2[x] = soma
  for x in estados:
    dic3[x] = dic2[x] / dic1[x]
  return dic3

soma24, total24, total_estados24, soma_estados24, media24 = 0, 0, {}, {}, {}
print(media_estado(2024, soma24, total24, total_estados24, soma_estados24, media24))

soma20, total20, total_estados20, soma_estados20, media20 = 0, 0, {}, {}, {}
print(media_estado(2020, soma20, total20, total_estados20, soma_estados20, media20))

soma16, total16, total_estados16, soma_estados16, media16 = 0, 0, {}, {}, {}
print(media_estado(2016, soma16, total16, total_estados16, soma_estados16, media16))

soma12, total12, total_estados12, soma_estados12, media12 = 0, 0, {}, {}, {}
print(media_estado(2012, soma12, total12, total_estados12, soma_estados12, media12))

soma08, total08, total_estados08, soma_estados08, media08 = 0, 0, {}, {}, {}
print(media_estado(2008, soma08, total08, total_estados08, soma_estados08, media08))

soma04, total04, total_estados04, soma_estados04, media04 = 0, 0, {}, {}, {}
print(media_estado(2004, soma04, total04, total_estados04, soma_estados04, media04))

soma00, total00, total_estados00, soma_estados00, media00 = 0, 0, {}, {}, {}
print(media_estado(2000, soma00, total00, total_estados00, soma_estados00, media00))

sns.lineplot(data=media24, x=media24.keys(), y=media24.values()).set(title='Média de partidos por coligação em 2024', xlabel='Estado', ylabel='Partidos por coligação')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()

sns.lineplot(data=media20, x=media20.keys(), y=media20.values(), color='red').set(title='Média de partidos por coligação em 2020', xlabel='Estado', ylabel='Partidos por coligação')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()

sns.lineplot(data=media16, x=media16.keys(), y=media16.values(), color='yellow').set(title='Média de partidos por coligação em 2016', xlabel='Estado', ylabel='Partidos por coligação')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()

sns.lineplot(data=media12, x=media12.keys(), y=media12.values(), color='purple').set(title='Média de partidos por coligação em 2012', xlabel='Estado', ylabel='Partidos por coligação')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()

sns.lineplot(data=media08, x=media08.keys(), y=media08.values(), color='orange').set(title='Média de partidos por coligação em 2008', xlabel='Estado', ylabel='Partidos por coligação')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()

sns.lineplot(data=media04, x=media04.keys(), y=media04.values(), color='pink').set(title='Média de partidos por coligação em 2004', xlabel='Estado', ylabel='Partidos por coligação')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()

sns.lineplot(data=media00, x=media00.keys(), y=media00.values(), color='gray').set(title='Média de partidos por coligação em 2000', xlabel='Estado', ylabel='Partidos por coligação')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()

anos = [2000, 2004, 2008, 2012, 2016, 2020, 2024]

def media_ano(estado, soma, total, dic1, dic2, dic3):
  for x in anos:
    for index, row in coligacao.iterrows():
      if row['SG_UF'] == estado and row['ANO_ELEICAO'] == x:
        total = total + 1
        soma = soma + 1
        dic1[x] = total
        dic2[x] = soma
        for y in str(row['DS_COMPOSICAO_COLIGACAO']):
          if y == '/':
            soma = soma + 1
            dic2[x] = soma
  for x in anos:
    dic3[x] = dic2[x] / dic1[x]
  return dic3

somaAC, totalAC, total_AC, soma_AC, media_AC = 0, 0, {}, {}, {}
print(media_ano('AC', somaAC, totalAC, total_AC, soma_AC, media_AC))

somaAL, totalAL, total_AL, soma_AL, media_AL = 0, 0, {}, {}, {}
print(media_ano('AL', somaAL, totalAL, total_AL, soma_AL, media_AL))

somaAM, totalAM, total_AM, soma_AM, media_AM = 0, 0, {}, {}, {}
print(media_ano('AM', somaAM, totalAM, total_AM, soma_AM, media_AM))

somaAP, totalAP, total_AP, soma_AP, media_AP = 0, 0, {}, {}, {}
print(media_ano('AP', somaAP, totalAP, total_AP, soma_AP, media_AP))

somaBA, totalBA, total_BA, soma_BA, media_BA = 0, 0, {}, {}, {}
print(media_ano('BA', somaBA, totalBA, total_BA, soma_BA, media_BA))

somaCE, totalCE, total_CE, soma_CE, media_CE = 0, 0, {}, {}, {}
print(media_ano('CE', somaCE, totalCE, total_CE, soma_CE, media_CE))

somaES, totalES, total_ES, soma_ES, media_ES = 0, 0, {}, {}, {}
print(media_ano('ES', somaES, totalES, total_ES, soma_ES, media_ES))

somaGO, totalGO, total_GO, soma_GO, media_GO = 0, 0, {}, {}, {}
print(media_ano('GO', somaGO, totalGO, total_GO, soma_GO, media_GO))

somaMA, totalMA, total_MA, soma_MA, media_MA = 0, 0, {}, {}, {}
print(media_ano('MA', somaMA, totalMA, total_MA, soma_MA, media_MA))

somaMG, totalMG, total_MG, soma_MG, media_MG = 0, 0, {}, {}, {}
print(media_ano('MG', somaMG, totalMG, total_MG, soma_MG, media_MG))

somaMS, totalMS, total_MS, soma_MS, media_MS = 0, 0, {}, {}, {}
print(media_ano('MS', somaMS, totalMS, total_MS, soma_MS, media_MS))

somaMT, totalMT, total_MT, soma_MT, media_MT = 0, 0, {}, {}, {}
print(media_ano('MT', somaMT, totalMT, total_MT, soma_MT, media_MT))

somaPA, totalPA, total_PA, soma_PA, media_PA = 0, 0, {}, {}, {}
print(media_ano('PA', somaPA, totalPA, total_PA, soma_PA, media_PA))

somaPB, totalPB, total_PB, soma_PB, media_PB = 0, 0, {}, {}, {}
print(media_ano('PB', somaPB, totalPB, total_PB, soma_PB, media_PB))

somaPE, totalPE, total_PE, soma_PE, media_PE = 0, 0, {}, {}, {}
print(media_ano('PE', somaPE, totalPE, total_PE, soma_PE, media_PE))

somaPI, totalPI, total_PI, soma_PI, media_PI = 0, 0, {}, {}, {}
print(media_ano('PI', somaPI, totalPI, total_PI, soma_PI, media_PI))

somaPR, totalPR, total_PR, soma_PR, media_PR = 0, 0, {}, {}, {}
print(media_ano('PR', somaPR, totalPR, total_PR, soma_PR, media_PR))

somaRJ, totalRJ, total_RJ, soma_RJ, media_RJ = 0, 0, {}, {}, {}
print(media_ano('RJ', somaRJ, totalRJ, total_RJ, soma_RJ, media_RJ))

somaRN, totalRN, total_RN, soma_RN, media_RN = 0, 0, {}, {}, {}
print(media_ano('RN', somaRN, totalRN, total_RN, soma_RN, media_RN))

somaRO, totalRO, total_RO, soma_RO, media_RO = 0, 0, {}, {}, {}
print(media_ano('RO', somaRO, totalRO, total_RO, soma_RO, media_RO))

somaRR, totalRR, total_RR, soma_RR, media_RR = 0, 0, {}, {}, {}
print(media_ano('RR', somaRR, totalRR, total_RR, soma_RR, media_RR))

somaRS, totalRS, total_RS, soma_RS, media_RS = 0, 0, {}, {}, {}
print(media_ano('RS', somaRS, totalRS, total_RS, soma_RS, media_RS))

somaSC, totalSC, total_SC, soma_SC, media_SC = 0, 0, {}, {}, {}
print(media_ano('SC', somaSC, totalSC, total_SC, soma_SC, media_SC))

somaSE, totalSE, total_SE, soma_SE, media_SE = 0, 0, {}, {}, {}
print(media_ano('SE', somaSE, totalSE, total_SE, soma_SE, media_SE))

somaSP, totalSP, total_SP, soma_SP, media_SP = 0, 0, {}, {}, {}
print(media_ano('SP', somaSP, totalSP, total_SP, soma_SP, media_SP))

somaTO, totalTO, total_TO, soma_TO, media_TO = 0, 0, {}, {}, {}
print(media_ano('TO', somaTO, totalTO, total_TO, soma_TO, media_TO))

sns.lineplot(data=media_AC, x=media_AC.keys(), y=media_AC.values(), color='blue').set(title='Média de partidos por coligação no Acre', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_AL, x=media_AL.keys(), y=media_AL.values(), color='yellow').set(title='Média de partidos por coligação em Alagoas', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_AM, x=media_AM.keys(), y=media_AM.values(), color='blue').set(title='Média de partidos por coligação em Amazonas', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_AP, x=media_AP.keys(), y=media_AP.values(), color='blue').set(title='Média de partidos por coligação em Amapá', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_BA, x=media_BA.keys(), y=media_BA.values(), color='yellow').set(title='Média de partidos por coligação na Bahia', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_CE, x=media_CE.keys(), y=media_CE.values(), color='yellow').set(title='Média de partidos por coligação no Ceará', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_ES, x=media_ES.keys(), y=media_ES.values(), color='pink').set(title='Média de partidos por coligação no Espírito Santo', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_GO, x=media_GO.keys(), y=media_GO.values(), color='orange').set(title='Média de partidos por coligação no Goiás', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_MA, x=media_MA.keys(), y=media_MA.values(), color='yellow').set(title='Média de partidos por coligação no Maranhão', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_MG, x=media_MG.keys(), y=media_MG.values(), color='pink').set(title='Média de partidos por coligação em Minas Gerais', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_MS, x=media_MS.keys(), y=media_MS.values(), color='orange').set(title='Média de partidos por coligação no Mato Grosso do Sul', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_MT, x=media_MT.keys(), y=media_MT.values(), color='orange').set(title='Média de partidos por coligação no Mato Grosso', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_PA, x=media_PA.keys(), y=media_PA.values(), color='blue').set(title='Média de partidos por coligação no Pará', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_PB, x=media_PB.keys(), y=media_PB.values(), color='yellow').set(title='Média de partidos por coligação na Paraíba', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_PE, x=media_PE.keys(), y=media_PE.values(), color='yellow').set(title='Média de partidos por coligação em Pernambuco', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_PI, x=media_PI.keys(), y=media_PI.values(), color='yellow').set(title='Média de partidos por coligação no Piauí', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_PR, x=media_PR.keys(), y=media_PR.values(), color='purple').set(title='Média de partidos por coligação no Paraná', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_RJ, x=media_RJ.keys(), y=media_RJ.values(), color='pink').set(title='Média de partidos por coligação no Rio de Janeiro', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_RN, x=media_RN.keys(), y=media_RN.values(), color='yellow').set(title='Média de partidos por coligação no Rio Grande do Norte', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_RO, x=media_RO.keys(), y=media_RO.values(), color='blue').set(title='Média de partidos por coligação em Rondônia', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_RR, x=media_RR.keys(), y=media_RR.values(), color='blue').set(title='Média de partidos por coligação em Roraima', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_RS, x=media_RS.keys(), y=media_RS.values(), color='purple').set(title='Média de partidos por coligação no Rio Grande do Sul', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_SC, x=media_SC.keys(), y=media_SC.values(), color='purple').set(title='Média de partidos por coligação em Santa Catarina', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_SE, x=media_SE.keys(), y=media_SE.values(), color='yellow').set(title='Média de partidos por coligação no Sergipe', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_SP, x=media_SP.keys(), y=media_SP.values(), color='pink').set(title='Média de partidos por coligação em São Paulo', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_TO, x=media_TO.keys(), y=media_TO.values(), color='blue').set(title='Média de partidos por coligação em Tocantins', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

capitais = ['RIO BRANCO', 'MACEIO', 'MACAPA', 'MANAUS', 'SALVADOR', 'FORTALEZA', 'VITORIA', 'GOIANIA', 'SAO LUIS', 'CUIABA', 'CAMPO GRANDE', 'BELO HORIZONTE', 'BELEM', 'JOAO PESSOA', 'CURITIBA', 'RECIFE', 'TERESINA', 'RIO DE JANEIRO', 'NATAL', 'PORTO ALEGRE', 'PORTO VELHO', 'BOA VISTA', 'FLORIANOPOLIS', 'SAO PAULO', 'ARACAJU', 'PALMAS']

def media_capitais(ano, soma, total, dic1, dic2, dic3):
  for x in capitais:
    for index, row in coligacao.iterrows():
      nm_ue_sem_acento = unicodedata.normalize('NFKD', str(row['NM_UE'])).encode('ASCII', 'ignore').decode('ASCII')
      if nm_ue_sem_acento == x and row['ANO_ELEICAO'] == ano:
        total = total + 1
        soma = soma + 1
        dic1[x] = total
        dic2[x] = soma
        for y in str(row['DS_COMPOSICAO_COLIGACAO']):
          if y == '/':
            soma = soma + 1
            dic2[x] = soma
  for x in capitais:
    dic3[x] = dic2[x] / dic1[x]
  return dic3

capsoma24, captotal24, captotal_estados24, capsoma_estados24, capmedia24 = 0, 0, {}, {}, {}
print(media_capitais(2024, capsoma24, captotal24, captotal_estados24, capsoma_estados24, capmedia24))

capsoma20, captotal20, captotal_estados20, capsoma_estados20, capmedia20 = 0, 0, {}, {}, {}
print(media_capitais(2020, capsoma20, captotal20, captotal_estados20, capsoma_estados20, capmedia20))

capsoma16, captotal16, captotal_estados16, capsoma_estados16, capmedia16 = 0, 0, {}, {}, {}
print(media_capitais(2016, capsoma16, captotal16, captotal_estados16, capsoma_estados16, capmedia16))

capsoma12, captotal12, captotal_estados12, capsoma_estados12, capmedia12 = 0, 0, {}, {}, {}
print(media_capitais(2012, capsoma12, captotal12, captotal_estados12, capsoma_estados12, capmedia12))

capsoma08, captotal08, captotal_estados08, capsoma_estados08, capmedia08 = 0, 0, {}, {}, {}
print(media_capitais(2008, capsoma08, captotal08, captotal_estados08, capsoma_estados08, capmedia08))

capsoma04, captotal04, captotal_estados04, capsoma_estados04, capmedia04 = 0, 0, {}, {}, {}
print(media_capitais(2004, capsoma04, captotal04, captotal_estados04, capsoma_estados04, capmedia04))

capsoma00, captotal00, captotal_estados00, capsoma_estados00, capmedia00 = 0, 0, {}, {}, {}
print(media_capitais(2000, capsoma00, captotal00, captotal_estados00, capsoma_estados00, capmedia00))

sns.lineplot(data=capmedia24, x=capmedia24.keys(), y=capmedia24.values()).set(title='Média de partidos por coligação em 2024 (capitais)', xlabel='Capital', ylabel='Partidos por coligação')
plt.xticks(rotation=90, ha='right')
plt.tight_layout()

sns.lineplot(data=capmedia20, x=capmedia20.keys(), y=capmedia20.values(), color='red').set(title='Média de partidos por coligação em 2020 (capitais)', xlabel='Capital', ylabel='Partidos por coligação')
plt.xticks(rotation=90, ha='right')
plt.tight_layout()

sns.lineplot(data=capmedia16, x=capmedia16.keys(), y=capmedia16.values(), color='yellow').set(title='Média de partidos por coligação em 2016 (capitais)', xlabel='Capital', ylabel='Partidos por coligação')
plt.xticks(rotation=90, ha='right')
plt.tight_layout()

sns.lineplot(data=capmedia12, x=capmedia12.keys(), y=capmedia12.values(), color='purple').set(title='Média de partidos por coligação em 2012 (capitais)', xlabel='Capital', ylabel='Partidos por coligação')
plt.xticks(rotation=90, ha='right')
plt.tight_layout()

sns.lineplot(data=capmedia08, x=capmedia08.keys(), y=capmedia08.values(), color='orange').set(title='Média de partidos por coligação em 2008 (capitais)', xlabel='Capital', ylabel='Partidos por coligação')
plt.xticks(rotation=90, ha='right')
plt.tight_layout()

sns.lineplot(data=capmedia04, x=capmedia04.keys(), y=capmedia04.values(), color='pink').set(title='Média de partidos por coligação em 2004 (capitais)', xlabel='Capital', ylabel='Partidos por coligação')
plt.xticks(rotation=90, ha='right')
plt.tight_layout()

sns.lineplot(data=capmedia00, x=capmedia00.keys(), y=capmedia00.values(), color='gray').set(title='Média de partidos por coligação em 2000 (capitais)', xlabel='Capital', ylabel='Partidos por coligação')
plt.xticks(rotation=90, ha='right')
plt.tight_layout()

def media_ano_cap(capital, soma, total, dic1, dic2, dic3):
  for x in anos:
    for index, row in coligacao.iterrows():
      nm_ue_sem_acento = unicodedata.normalize('NFKD', str(row['NM_UE'])).encode('ASCII', 'ignore').decode('ASCII')
      if nm_ue_sem_acento == capital and row['ANO_ELEICAO'] == x:
        total = total + 1
        soma = soma + 1
        dic1[x] = total
        dic2[x] = soma
        for y in str(row['DS_COMPOSICAO_COLIGACAO']):
          if y == '/':
            soma = soma + 1
            dic2[x] = soma
  for x in anos:
    dic3[x] = dic2[x] / dic1[x]
  return dic3

somaRioBranco, totalRioBranco, total_RioBranco, soma_RioBranco, media_RioBranco = 0, 0, {}, {}, {}
print(media_ano_cap('RIO BRANCO', somaRioBranco, totalRioBranco, total_RioBranco, soma_RioBranco, media_RioBranco))

somaMaceio, totalMaceio, total_Maceio, soma_Maceio, media_Maceio = 0, 0, {}, {}, {}
print(media_ano_cap('MACEIO', somaMaceio, totalMaceio, total_Maceio, soma_Maceio, media_Maceio))

somaMacapa, totalMacapa, total_Macapa, soma_Macapa, media_Macapa = 0, 0, {}, {}, {}
print(media_ano_cap('MACAPA', somaMacapa, totalMacapa, total_Macapa, soma_Macapa, media_Macapa))

somaManaus, totalManaus, total_Manaus, soma_Manaus, media_Manaus = 0, 0, {}, {}, {}
print(media_ano_cap('MANAUS', somaManaus, totalManaus, total_Manaus, soma_Manaus, media_Manaus))

somaSalvador, totalSalvador, total_Salvador, soma_Salvador, media_Salvador = 0, 0, {}, {}, {}
print(media_ano_cap('SALVADOR', somaSalvador, totalSalvador, total_Salvador, soma_Salvador, media_Salvador))

somaFortaleza, totalFortaleza, total_Fortaleza, soma_Fortaleza, media_Fortaleza = 0, 0, {}, {}, {}
print(media_ano_cap('FORTALEZA', somaFortaleza, totalFortaleza, total_Fortaleza, soma_Fortaleza, media_Fortaleza))

somaVitoria, totalVitoria, total_Vitoria, soma_Vitoria, media_Vitoria = 0, 0, {}, {}, {}
print(media_ano_cap('VITORIA', somaVitoria, totalVitoria, total_Vitoria, soma_Vitoria, media_Vitoria))

somaGoiania, totalGoiania, total_Goiania, soma_Goiania, media_Goiania = 0, 0, {}, {}, {}
print(media_ano_cap('GOIANIA', somaGoiania, totalGoiania, total_Goiania, soma_Goiania, media_Goiania))

somaSaoLuis, totalSaoLuis, total_SaoLuis, soma_SaoLuis, media_SaoLuis = 0, 0, {}, {}, {}
print(media_ano_cap('SAO LUIS', somaSaoLuis, totalSaoLuis, total_SaoLuis, soma_SaoLuis, media_SaoLuis))

somaCuiaba, totalCuiaba, total_Cuiaba, soma_Cuiaba, media_Cuiaba = 0, 0, {}, {}, {}
print(media_ano_cap('CUIABA', somaCuiaba, totalCuiaba, total_Cuiaba, soma_Cuiaba, media_Cuiaba))

somaCampoGrande, totalCampoGrande, total_CampoGrande, soma_CampoGrande, media_CampoGrande = 0, 0, {}, {}, {}
print(media_ano_cap('CAMPO GRANDE', somaCampoGrande, totalCampoGrande, total_CampoGrande, soma_CampoGrande, media_CampoGrande))

somaBeloHorizonte, totalBeloHorizonte, total_BeloHorizonte, soma_BeloHorizonte, media_BeloHorizonte = 0, 0, {}, {}, {}
print(media_ano_cap('BELO HORIZONTE', somaBeloHorizonte, totalBeloHorizonte, total_BeloHorizonte, soma_BeloHorizonte, media_BeloHorizonte))

somaBelem, totalBelem, total_Belem, soma_Belem, media_Belem = 0, 0, {}, {}, {}
print(media_ano_cap('BELEM', somaBelem, totalBelem, total_Belem, soma_Belem, media_Belem))

somaJoaoPessoa, totalJoaoPessoa, total_JoaoPessoa, soma_JoaoPessoa, media_JoaoPessoa = 0, 0, {}, {}, {}
print(media_ano_cap('JOAO PESSOA', somaJoaoPessoa, totalJoaoPessoa, total_JoaoPessoa, soma_JoaoPessoa, media_JoaoPessoa))

somaCuritiba, totalCuritiba, total_Curitiba, soma_Curitiba, media_Curitiba = 0, 0, {}, {}, {}
print(media_ano_cap('CURITIBA', somaCuritiba, totalCuritiba, total_Curitiba, soma_Curitiba, media_Curitiba))

somaRecife, totalRecife, total_Recife, soma_Recife, media_Recife = 0, 0, {}, {}, {}
print(media_ano_cap('RECIFE', somaRecife, totalRecife, total_Recife, soma_Recife, media_Recife))

somaTeresina, totalTeresina, total_Teresina, soma_Teresina, media_Teresina = 0, 0, {}, {}, {}
print(media_ano_cap('TERESINA', somaTeresina, totalTeresina, total_Teresina, soma_Teresina, media_Teresina))

somaRiodeJaneiro, totalRiodeJaneiro, total_RiodeJaneiro, soma_RiodeJaneiro, media_RiodeJaneiro = 0, 0, {}, {}, {}
print(media_ano_cap('RIO DE JANEIRO', somaRiodeJaneiro, totalRiodeJaneiro, total_RiodeJaneiro, soma_RiodeJaneiro, media_RiodeJaneiro))

somaNatal, totalNatal, total_Natal, soma_Natal, media_Natal = 0, 0, {}, {}, {}
print(media_ano_cap('NATAL', somaNatal, totalNatal, total_Natal, soma_Natal, media_Natal))

somaPortoAlegre, totalPortoAlegre, total_PortoAlegre, soma_PortoAlegre, media_PortoAlegre = 0, 0, {}, {}, {}
print(media_ano_cap('PORTO ALEGRE', somaPortoAlegre, totalPortoAlegre, total_PortoAlegre, soma_PortoAlegre, media_PortoAlegre))

somaPortoVelho, totalPortoVelho, total_PortoVelho, soma_PortoVelho, media_PortoVelho = 0, 0, {}, {}, {}
print(media_ano_cap('PORTO VELHO', somaPortoVelho, totalPortoVelho, total_PortoVelho, soma_PortoVelho, media_PortoVelho))

somaBoaVista, totalBoaVista, total_BoaVista, soma_BoaVista, media_BoaVista = 0, 0, {}, {}, {}
print(media_ano_cap('BOA VISTA', somaBoaVista, totalBoaVista, total_BoaVista, soma_BoaVista, media_BoaVista))

somaFlorianopolis, totalFlorianopolis, total_Florianopolis, soma_Florianopolis, media_Florianopolis = 0, 0, {}, {}, {}
print(media_ano_cap('FLORIANOPOLIS', somaFlorianopolis, totalFlorianopolis, total_Florianopolis, soma_Florianopolis, media_Florianopolis))

somaSaoPaulo, totalSaoPaulo, total_SaoPaulo, soma_SaoPaulo, media_SaoPaulo = 0, 0, {}, {}, {}
print(media_ano_cap('SAO PAULO', somaSaoPaulo, totalSaoPaulo, total_SaoPaulo, soma_SaoPaulo, media_SaoPaulo))

somaAracaju, totalAracaju, total_Aracaju, soma_Aracaju, media_Aracaju = 0, 0, {}, {}, {}
print(media_ano_cap('ARACAJU', somaAracaju, totalAracaju, total_Aracaju, soma_Aracaju, media_Aracaju))

somaPalmas, totalPalmas, total_Palmas, soma_Palmas, media_Palmas = 0, 0, {}, {}, {}
print(media_ano_cap('PALMAS', somaPalmas, totalPalmas, total_Palmas, soma_Palmas, media_Palmas))

sns.lineplot(data=media_RioBranco, x=media_RioBranco.keys(), y=media_RioBranco.values(), color='blue').set(title='Média de partidos por coligação em Rio Branco', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_Maceio, x=media_Maceio.keys(), y=media_Maceio.values(), color='yellow').set(title='Média de partidos por coligação em Maceió', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_Manaus, x=media_Manaus.keys(), y=media_Manaus.values(), color='blue').set(title='Média de partidos por coligação em Manaus', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_Macapa, x=media_Macapa.keys(), y=media_Macapa.values(), color='blue').set(title='Média de partidos por coligação em Macapá', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_Salvador, x=media_Salvador.keys(), y=media_Salvador.values(), color='yellow').set(title='Média de partidos por coligação em Salvador', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_Fortaleza, x=media_Fortaleza.keys(), y=media_Fortaleza.values(), color='yellow').set(title='Média de partidos por coligação em Fortaleza', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_Vitoria, x=media_Vitoria.keys(), y=media_Vitoria.values(), color='pink').set(title='Média de partidos por coligação em Vitória', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_Goiania, x=media_Goiania.keys(), y=media_Goiania.values(), color='orange').set(title='Média de partidos por coligação em Goiânia', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_SaoLuis, x=media_SaoLuis.keys(), y=media_SaoLuis.values(), color='yellow').set(title='Média de partidos por coligação em São Luís', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_BeloHorizonte, x=media_BeloHorizonte.keys(), y=media_BeloHorizonte.values(), color='pink').set(title='Média de partidos por coligação em Belo Horizonte', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_CampoGrande, x=media_CampoGrande.keys(), y=media_CampoGrande.values(), color='orange').set(title='Média de partidos por coligação em Campo Grande', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_Cuiaba, x=media_Cuiaba.keys(), y=media_Cuiaba.values(), color='orange').set(title='Média de partidos por coligação em Cuiabá', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_Belem, x=media_Belem.keys(), y=media_Belem.values(), color='blue').set(title='Média de partidos por coligação em Belém', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_JoaoPessoa, x=media_JoaoPessoa.keys(), y=media_JoaoPessoa.values(), color='yellow').set(title='Média de partidos por coligação em João Pessoa', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_Recife, x=media_Recife.keys(), y=media_Recife.values(), color='yellow').set(title='Média de partidos por coligação em Recife', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_Teresina, x=media_Teresina.keys(), y=media_Teresina.values(), color='yellow').set(title='Média de partidos por coligação em Teresina', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_Curitiba, x=media_Curitiba.keys(), y=media_Curitiba.values(), color='purple').set(title='Média de partidos por coligação em Curitiba', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_RiodeJaneiro, x=media_RiodeJaneiro.keys(), y=media_RiodeJaneiro.values(), color='pink').set(title='Média de partidos por coligação no Rio de Janeiro', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_Natal, x=media_Natal.keys(), y=media_Natal.values(), color='yellow').set(title='Média de partidos por coligação em Natal', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_PortoVelho, x=media_PortoVelho.keys(), y=media_PortoVelho.values(), color='blue').set(title='Média de partidos por coligação em Porto Velho', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_BoaVista, x=media_BoaVista.keys(), y=media_BoaVista.values(), color='blue').set(title='Média de partidos por coligação em Boa Vista', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_PortoAlegre, x=media_PortoAlegre.keys(), y=media_PortoAlegre.values(), color='purple').set(title='Média de partidos por coligação em Porto Alegre', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_Florianopolis, x=media_Florianopolis.keys(), y=media_Florianopolis.values(), color='purple').set(title='Média de partidos por coligação em Florianópolis', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_Aracaju, x=media_Aracaju.keys(), y=media_Aracaju.values(), color='yellow').set(title='Média de partidos por coligação em Aracaju', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_SaoPaulo, x=media_SaoPaulo.keys(), y=media_SaoPaulo.values(), color='pink').set(title='Média de partidos por coligação em São Paulo', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))

sns.lineplot(data=media_Palmas, x=media_Palmas.keys(), y=media_Palmas.values(), color='blue').set(title='Média de partidos por coligação em Palmas', xlabel='Ano', ylabel='Partidos por coligação')
plt.tight_layout()
plt.xticks(range(2000, 2025, 4))